### ISSUE TITLE
/revive command does not teleport to correct Y axis

### ISSUE THREAD

**Issue by Bialogs** [MatthewDwyer/botman#4]
I am assuming that the `y` coordinate, as it is in Unity, is the vertical.

The `/revive` command will place players on the correct `x,z` location but the `y` location is bad. For example, `/revive` will teleport a player on top of a building if a player dies on the first floor.

I think I've tracked the actual call to teleport down [here](https://github.com/MatthewDwyer/botman/blob/master/mudlet/profiles/newbot/scripts/chat/gmsg_teleports.lua#L914-L925).

From the SQL query you are grabbing a specific `x,z` value but no `y` value. Based on in-game behavior it seems like the `y` ends up being the tallest block at a specific `x,z` but I'm not sure how you'd ever get that information. The `y` coordinate is only ever set [here](https://github.com/MatthewDwyer/botman/blob/83149aba8d164caaaff08f1b52e9801a86efecc9/mudlet/profiles/newbot/scripts/triggers/player_info.lua#L1407) and this `y` coordinate being saved into the database is based off of `name_table[4]`. I really can't find where the `line` that `name_table` is based off of but if it has to do with a chat line, that would be the player's current position, correct?

Could the solution be adding `((abs(y - " .. players[chatvars.playerid].deathY .. ") > 0 and abs(y - " .. players[chatvars.playerid].deathY .. ") < 50)` similar to the other coordinates so a specific `y` value matches?

Alternatively, why not just teleport the player to their death location using the already available information in  `players[chatvars.playerid].death{X,Y,Z}` which is recorded accurately at death time and avoid the query altogether?

**Comment by MatthewDwyer** [comment]
The reason it does the query is I don't send the player back to the exact spot where they died but nearby.  Most of the time there's no problem with that.  Occasionally the terrain might interfere such as with a low ceiling in a cave.  I assume that something like spikes killed them and instead of returning them there, I look at their recorded steps within a radius of that spot and send them there as I am assuming those steps were safer than the spot where they died.
